Fix MergedJobConfig class to enable printing arguments during training (#1158)
## Context

The `MergedJobConfig` class doesn't have method to_dict(), so when the
job_config is an instance of `MergeJobConfig`, we will run into the
following error when running with `--job.print_args`.
```
AttributeError: 'MergedJobConfig' object has no attribute 'to_dict'
```